name: Issue and PR Auto Comment

on:
  issues:
    types: [closed]
  pull_request:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment when issue is closed
      if: github.event_name == 'issues' && github.event.action == 'closed'
      uses: actions/github-script@v7
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "The issue is now resolved."
          })

    - name: Congratulate on first PR
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pulls } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });

          const user = context.payload.pull_request.user.login;
          const userPulls = pulls.filter(pr => pr.user.login === user);

          if (userPulls.length === 1) {
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 Congratulations @${user} on your first pull request!`
            });
          }
